data:
  raw:   '../data/raw/flight_rating.csv'
  clean: '../data/clean/flight_rating_clean.csv'
  train: '../data/scaled/flight_rating_train.csv'
  test:  '../data/scaled/flight_rating_test.csv'


testsplit:
  random_state: 42
  test_size:    0.25

encoder:
  onehot: '../encoder/onehot.pkl'

scaler:
  standard: '../scaler/standard_scaler.pkl'
  minmax:   '../scaler/minmax_scaler.pkl'
  power:    '../scaler/power_transformer.pkl'

model:
  logReg: '../models/logistic_regressor.pkl'
  randForest: '../models/random_forest.pkl'
  knn:    '../models/knn_classifier.pkl'
