data:
  # Raw dataset
  raw:   '../data/raw/flight_rating.csv'
  # Cleaned dataset
  clean: '../data/clean/flight_rating_clean.csv'
  # Scaled and encoded dataset
  trans: '../data/clean/flight_rating_transformed.csv'


testsplit:
  random_state: 42
  test_size:    0.25

#encoder:
#  onehot: '../encoders/onehot.pkl'

#scaler:
#  standard: '../scalers/standard.pkl'
#  minmax: '../scalers/minmax.pkl'

#model:
#  KNN: '../models/knn.pkl'
